### ISSUE TITLE
Adicionar link/URL para documentação

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/doc-gerenciador-conecta#3]

**Comment by orair** [comment]
@caduvieira, onde você quer que seja adicionado o link/URL para documentação? no README?
Atualmente está em https://documentacao-do-gerenciador-de-apis-do-conecta.readthedocs.io mas pretendemos criar um CNAME

**Comment by caduvieira** [comment]
Adicionei no about. Depois altere por favor. Obrigado!
